"""Ajout du champ D'après dans la création de la recette

Revision ID: bcdf0b2f0aec
Revises: bebf264b30f9
Create Date: 2026-02-22 22:50:35.765820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdf0b2f0aec'
down_revision = 'bebf264b30f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
