"""add is_favorite to recipes

Revision ID: bebf264b30f9
Revises: c0745d4076aa
Create Date: 2026-02-20 18:22:00.581488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebf264b30f9'
down_revision = 'c0745d4076aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_recipes_is_favorite'), ['is_favorite'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_is_favorite'))
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
